"""
clean up autogenerated json files

- add task name

"""


import os
import json
from utils import locate

taskname_dict = {
    'breathhold': 'Breath holding task',
    'dots': 'Dot motion stop-signal task',
    'nback': 'N-back task',
    'rest': 'Resting fmri',
    'retinotopy': 'Retinotopic mapping',
    'objects': 'Object recognition task',
    'language': 'Sentence processing task',
    'spatialwm': 'Spatial working memory task'
}

def fix_json(data, verbose=True):
    if 'TaskName' in data:
        origname = data['TaskName'].replace('TODO: full task name for ', '')
        if origname in taskname_dict:
            data['TaskName'] = taskname_dict[origname]
            if verbose:
                print('replaced', origname, 'with', data['TaskName'])
    return(data)

if __name__ == "__main__":
    bidsdir = '/home/poldrack/data/fmri-handbook-2e-data/bids'
    # ignore files in heudiconv dir
    jsonfiles = [i for i in locate('*.json', bidsdir) if '.heudiconv' not in i]
    for j in jsonfiles:
        with open(j) as f:
            jsondata = json.load(f)
        fixed_json = fix_json(jsondata)
        with open(j, 'w') as f:
            json.dump(fixed_json, f)